export const patients = [
  {
    name: {
      first: "John",
      last: "Doe",
      middle: "A",
    },
    address: {
      line1: "123 Main St",
      city: "Metropolis",
      province: "State",
    },
    _id: "670a8e094111ab896fe2d5a7",
    contactNumber: "09876546799",
    __v: 0,
    age: 34,
    birthdate: "1990-01-01T00:00:00.000Z",
    email: "johndoe@example.com",
    facebookName: "john.doe",
    lastConsultId: null,
    occupation: "Software Engineer",
    sex: "Male",
  },
  {
    name: {
      first: "John",
      last: "Doe",
      middle: "A",
    },
    address: {
      line1: "123 Main St",
      city: "Metropolis",
      province: "State",
    },
    _id: "670a92364111ab896fe6606c",
    contactNumber: "undefined",
    __v: 0,
    age: 34,
    birthdate: "1990-01-01T00:00:00.000Z",
    email: "johndoe@example.com",
    facebookName: "john.doe",
    lastConsultId: null,
    occupation: "Software Engineer",
    sex: "Male",
  },
  {
    name: {
      first: "John",
      last: "Doe",
      middle: "A",
    },
    address: {
      line1: "123 Main St",
      city: "Metropolis",
      province: "State",
    },
    _id: "670a930c4111ab896fe70f09",
    contactNumber: "09175549445",
    __v: 0,
    age: 34,
    birthdate: "1990-01-01T00:00:00.000Z",
    email: "johndoe@example.com",
    facebookName: "john.doe",
    lastConsultId: null,
    occupation: "Software Engineer",
    sex: "Male",
  },
  {
    name: {
      first: "John",
      last: "Doe",
      middle: "A",
    },
    address: {
      line1: "123 Main St",
      city: "Metropolis",
      province: "State",
    },
    _id: "670ab42a4111ab896f073990",
    contactNumber: "09175549123",
    __v: 0,
    age: 34,
    birthdate: "1990-01-01T00:00:00.000Z",
    email: "johndoe@example.com",
    facebookName: "john.doe",
    lastConsultId: null,
    occupation: "Software Engineer",
    sex: "Male",
  },
  {
    name: {
      first: "John",
      last: "Doe",
      middle: "A",
    },
    address: {
      line1: "123 Main St",
      city: "Metropolis",
      province: "State",
    },
    _id: "670ab4844111ab896f079846",
    contactNumber: "9175549123",
    __v: 0,
    age: 34,
    birthdate: "1990-01-01T00:00:00.000Z",
    email: "johndoe@example.com",
    facebookName: "john.doe",
    lastConsultId: null,
    occupation: "Software Engineer",
    sex: "Male",
  },
  {
    name: {
      first: "Jamir",
      last: "Jasper",
      middle: "Sauquillo",
    },
    address: {
      line1: "123 Main St",
      city: "Metropolis",
      province: "State",
    },
    _id: "670aba7f4111ab896f0d85f3",
    contactNumber: "09175549444",
    __v: 0,
    age: 34,
    birthdate: "1990-01-01T00:00:00.000Z",
    email: "johndoe@example.com",
    facebookName: "jjamir",
    lastConsultId: null,
    occupation: "Software Engineer",
    sex: "Male",
  },
  {
    name: {
      first: "Raia",
      last: "Quitoriano",
      middle: "Sampang",
    },
    address: {
      line1: "198 Aguinaldo St. Binakayan, Kawit, Cavite",
      city: "The quick brown fox jumps over the lazy dog",
      province: "The quick brown fox jumps over the lazy dog",
    },
    _id: "670abc224111ab896f0f1ca4",
    contactNumber: "09157181642",
    __v: 0,
    age: 34,
    birthdate: "1990-01-01T00:00:00.000Z",
    email: "raiaquitoriano@gmail.com",
    facebookName: "raiaqt",
    lastConsultId: null,
    occupation: "Software Engineer",
    sex: "Female",
  },
  {
    name: {
      first: "John",
      last: "Doe",
      middle: "A",
    },
    address: {
      line1: "123 Main St",
      city: "Metropolis",
      province: "State",
    },
    _id: "670abd3a4111ab896f102457",
    contactNumber: "9157181642",
    __v: 0,
    age: 34,
    birthdate: "1990-01-01T00:00:00.000Z",
    email: "johndoe@example.com",
    facebookName: "john.doe",
    lastConsultId: null,
    occupation: "Software Engineer",
    sex: "Male",
  },
  {
    name: {
      first: "John",
      last: "Doe",
      middle: "A",
    },
    address: {
      line1: "123 Main St",
      city: "Metropolis",
      province: "State",
    },
    _id: "670b449b4111ab896f887617",
    contactNumber: "09175549999",
    __v: 0,
    age: 34,
    birthdate: "1990-01-01T00:00:00.000Z",
    email: "johndoe@example.com",
    facebookName: "john.doe",
    lastConsultId: null,
    occupation: "Software Engineer",
    sex: "Male",
  },
  {
    name: {
      first: "John",
      last: "Jamir",
      middle: "A",
    },
    address: {
      line1: "123 Main St",
      city: "Metropolis",
      province: "State",
    },
    _id: "670b46794111ab896f8a1197",
    contactNumber: "9175549999",
    __v: 0,
    age: 34,
    birthdate: "1990-01-01T00:00:00.000Z",
    email: "johndoe@example.com",
    facebookName: "john.doe",
    lastConsultId: null,
    occupation: "Software Engineer",
    sex: "Male",
  },
  {
    name: {
      first: "Emma",
      last: "Jamir",
      middle: "Sauquillo",
    },
    address: {
      line1: "123 Main St",
      city: "Metropolis",
      province: "State",
    },
    _id: "670bc7684111ab896f0ea83e",
    contactNumber: "09175128432",
    __v: 0,
    age: 34,
    birthdate: "1990-01-01T00:00:00.000Z",
    email: "johndoe@example.com",
    facebookName: "emmajamir",
    lastConsultId: null,
    occupation: "Software Engineer",
    sex: "Male",
  },
  {
    name: {
      first: "Raia",
      last: "Quitoriano",
      middle: "Sampang",
    },
    address: {
      line1: "123 Main St",
      city: "Metropolis",
      province: "State",
    },
    _id: "671d238569b0020589294281",
    contactNumber: "09957181642",
    __v: 0,
    age: 26,
    birthdate: "1996-02-12T00:00:00.000Z",
    email: "rsquitoriano@gmail.com",
    facebookName: "Raia Quitoriano",
    lastConsultId: null,
    occupation: "Software Engineer",
    sex: "Female",
  },
];

export const patientDefinition = {
  type: "object",
  properties: {
    id: {
      type: "string",
      description: "ID",
    },
    name: {
      type: "object",
      description: "Name",
      properties: {
        first: {
          type: "string",
        },
        middle: {
          type: "string",
        },
        last: {
          type: "string",
        },
      },
    },
    address: {
      type: "object",
      description: "Address",
      properties: {
        line1: {
          type: "string",
        },
        city: {
          type: "string",
        },
        province: {
          type: "string",
        },
      },
    },
    contactNumber: {
      type: "string",
      description: "Contact number",
    },
    age: {
      type: "integer",
      description: "Age",
    },
    birthdate: {
      type: "string",
      format: "date",
      description: "Birth date",
    },
    email: {
      type: "string",
      format: "email",
      description: "Email address",
    },
    facebookName: {
      type: "string",
      description: "Facebook",
    },
    lastConsultId: {
      type: "string",
      description: "Last consult ID",
    },
    occupation: {
      type: "string",
      description: "Occupation",
    },
    sex: {
      type: "string",
      description: "Patient's gender",
      enum: ["Male", "Female"],
    },
  },
};
